import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';
import Footer from "@/components/Footer";
import Menu from "@/components/Menu";

const roboto = localFont({
  src: "../fonts/roboto-latin-wght-normal.woff2",
  variable: "--font-roboto",
  weight: "100 900",
  style: "normal",
  display: "swap",
})

const openSans = localFont({
  src: "../fonts/open-sans-latin-wght-normal.woff2",
  variable: "--font-openSans",
  weight: "100 900",
  style: "normal",
  display: "swap",
})

const inter = localFont({
  src: "../fonts/inter-latin-wght-normal.woff2",
  variable: "--font-inter",
  weight: "100 900",
  style: "normal",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontClass = `${roboto.variable} ${openSans.variable} ${inter.variable} antialiased flex flex-col justify-start items-center w-full min-h-screen font-inter`;
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      
      <body  className={`${fontClass} min-h-screen flex flex-col`}>
        <Menu />
        <main className="grow flex flex-col w-full px-1 mt-12">
        {children}
        </main>
        <Footer />
        </body>
      
    </html>
  );
}
